name="ygorg-frontend-sk"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
NODE_VERSION = "22.11.0"
PNPM_VERSION = "9.12.3"

[build]
command = "pnpm run build"
