query HomePagePosts($categories: [String] = []) {
  categories(where: { name: $categories }) {
    edges {
      node {
        name
        databaseId
        posts {
          edges {
            cursor
            node {
              title
              slug
              content
              dateGmt
              author {
                node {
                  name
                  uri
                }
              }
              featuredImage {
                node {
                  mediaItemUrl
                  altText
                  mediaDetails {
                    height
                    width
                  }
                }
              }
              categories {
                nodes {
                  name
                  slug
                }
              }
            }
          }
        }
      }
    }
  }
}
