query Post($slug: ID!) {
  post(id: $slug, idType: SLUG) {
    id
    title
    featuredImage {
      node {
        link
        sourceUrl
      }
    }
    content
    author {
      node {
        name
      }
    }
  }
}
